service: sherlock
runtime: python
env: flex
entrypoint: python application/main.py

runtime_config:
  python_version: 2

env_variables:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "9GAfs882PI1t9MDG"
  POSTGRES_DBNAME: "prices_prod"
  POSTGRES_HOST: "/cloudsql/panprices:europe-west1:panprices-psql"

beta_settings:
  cloud_sql_instances: panprices:europe-west1:panprices-psql