from pricerunner_fetchers import fetch_product_id
from pricerunner_fetchers import fetch_product_offers
from database_fetchers import fetch_products_without_pricerunner
from database_fetchers import fetch_pricerunner_products
from database_fetchers import fetch_products_without_amazon
from database_fetchers import fetch_amazon_products
from database_fetchers import fetch_products_without_ebay
from database_fetchers import fetch_products_without_kelkoo
from amazon_fetchers import search_for_product
from amazon_fetchers import search_for_offer
from amazon_fetchers import fetch_amazon_price
from currency_fetchers import fetch_exchange_rate
from ebay_fetchers import search_for_offer as search_for_e_offer
from kelkoo_fetchers import search_for_offer as search_for_k_offer
from prisjakt_fetchers import get_products
from database_fetchers import fetch_products_without_prisjakt
from database_fetchers import fetch_prisjakt_products
from prisjakt_fetchers import fetch_prisjakt_product_offers