from pricerunner_fetchers import fetch_product_id
from pricerunner_fetchers import fetch_product_offers
from database_fetchers import fetch_products_without_pricerunner
from database_fetchers import fetch_pricerunner_products
from database_fetchers import fetch_products_without_amazon
from database_fetchers import fetch_amazon_products
from database_fetchers import fetch_products_without_ebay
from database_fetchers import fetch_products_without_kelkoo
from database_fetchers import fetch_products_with_pj_images
from amazon_fetchers import search_for_product
from amazon_fetchers import search_for_offer
from amazon_fetchers import fetch_amazon_price
from currency_fetchers import fetch_exchange_rate
from ebay_fetchers import search_for_offer as search_for_e_offer
from kelkoo_fetchers import search_for_offer as search_for_k_offer
from prisjakt_fetchers import get_products
from database_fetchers import fetch_products_without_prisjakt
from database_fetchers import fetch_prisjakt_products
from database_fetchers import fetch_categories
from prisjakt_fetchers import fetch_prisjakt_product_offers
from forex_fetchers import get_latest_forex
from forex_fetchers import get_latest_exchange_rate
from database_fetchers import fetch_retailers_without_trustpilot
from trustpilot_fetchers import fetch_trustpilot_data
from database_fetchers import fetch_retailers_without_alexa
from alexa_fetchers import fetch_alexa_data